### ISSUE TITLE
Cannot find zkevm-node

### ISSUE THREAD

**Issue by avenbreaks** [0xPolygonHermez/zkevm-node#1353]
When im trying to build on cloud but eror for build 

`docker run --rm hermeznetwork/zkevm-node:latest sh -c "/app/zkevm-node encryptKey --pk=xxxxxxx --pw=xxxxx --output=./keystore; cat ./keystore/*" > acc.keystore`

`cat: can't open './keystore/*': No such file or directory`

`docker run --rm -v /$HOME/zkevm-node/config.toml:/app/config.toml hermeznetwork/zkevm-node:latest sh -c "./zkevm-node register --cfg=/app/config.toml --network=internaltestnet --y 167.71.195.248"`

`sh: ./zkevm-node: not found
`

**Comment by arnaubennassar** [comment]
I would strongly suggest to use the provided docker-compose, if this is not an option, you can still use it for reference on how to run the docker command.

In this particular case, it looks like you should use `/app/zkevm-node` instead of `./zkevm-node`
https://github.com/0xPolygonHermez/zkevm-node/blob/develop/docker-compose.yml#L19
