### ISSUE TITLE
Review need for executor

### ISSUE THREAD

**Issue by arnaubennassar** [0xPolygonHermez/zkevm-node#1745]
The following components shouldn't need executor:

- [ ] AGGREGATOR
- [ ] ETHTXMANAGER
- [ ] L2GASPRICER

We need to review if this components can start without executor

**Comment by tclemos** [comment]
Any component that depends on the `State`, will depend on the `Executor` automatically.
Also, the `State` only allows the component to start after it connects to the `Executor`, if it does not connect, it breaks the component execution.

In order to allow components to access the `State` without having to depend on the `Executor`, we need to make it optional during the `State` initialization and double-check it in all the `Executor` calls, providing a specific error for this problem, similar to the work we did in the `Etherman` working as read-only.

**Comment by ToniRamirezM** [comment]
Implemented in PR #1995
