### ISSUE TITLE
Feature Request: Return Major.Minor.Patch versioning to JSON-RPC call web3_clientVersion 

### ISSUE THREAD

**Issue by cg-polygon** [0xPolygonHermez/zkevm-node#1972]
It would be helpful to have more precise versioning info on web3_clientVersion JSON-RPC calls.

## Current State
When calling the `web3_clientVersion` method of the JSON-RPC, `Polygon Hermez zkEVM/v2.0.0` is currently returned.

### Request
```
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":83}' http://localhost:8545
```
### Response
```
{"jsonrpc":"2.0","id":83,"result":"Polygon Hermez zkEVM/v2.0.0"}
```

## Expected State
It would be helpful to return something closed to the current client versions. Something like `Polygon zkEVM Node: v0.0.3-RC36 Prover: v0.0.3-RC35` This would be especially useful for those managing large fleets of nodes ensure their software is up to date.

**Comment by tclemos** [comment]
That makes sense, when we implemented this endpoint we didn't have decided yet how to handle the version and we only had the definition of the protocol version. The binary already has this information when it is started, I think we can share this information with the jRPC server and return it when this endpoint is called.

I've added the tags to ensure the issue is considered in our filters and I'll take a look at it as soon as possible accordingly to the priorities.

Thanks for pointing this out.
