### ISSUE TITLE
 zkevm-rpc.com not responding or the execution times are too high

### ISSUE THREAD

**Issue by eduadiez** [0xPolygonHermez/zkevm-node#2161]
#### System information

zkEVM Node version: `v0.0.7`
OS & Version: `Linux`
Commit hash : 
Network: `Mainnet`

#### Expected behaviour

the rpc should respond to requests and not have high response times.

#### Actual behaviour

quickswap guys report these results:

```
[qperp-price-updater-1] [2023-06-02 14:29:00] 14:29:00 0|index | Position Request 1135 1151 562 564
[qperp-price-updater-1] [2023-06-02 14:29:00] 14:29:00 0|index | lastUpdate 2:26:04 PM
[qperp-price-updater-1] [2023-06-02 14:29:05] 14:29:05 0|index | 1685716142 Sending setPricesWithBitsAndExecute... 3.542
[qperp-price-updater-1] [2023-06-02 14:30:00] 14:30:00 0|index | lastUpdate 2:29:44 PM

 [2023-06-02 14:38:27] 14:38:27 0|index | 1685716699 Sending setPricesWithBitsAndExecute... 2.321
 [2023-06-02 14:40:55] 14:40:55 0|index | 1685716699 Sent! Duration: 154.696 second
 [2023-06-02 14:40:57] 14:40:57 0|index | 1685716699 setPricesWithBitsAndExecute gas used: 51626 txHash: 0xc3cbdec40b7f0193a0e6abea27d3f19d83556463ac0be5d0a3dc35f492a5d5ea
```

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by agnusmor** [comment]
From the sequencer side it seems has been processed:

[https://app.datadoghq.com/logs?query=service%3Azkevm-mainnet%200xc3cbdec40b7f0193a0e6[…]z=stream&from_ts=1685549826179&to_ts=1685722626179&live=true](https://app.datadoghq.com/logs?query=service%3Azkevm-mainnet%200xc3cbdec40b7f0193a0e6abea27d3f19d83556463ac0be5d0a3dc35f492a5d5ea%20&additional_filters=%5B%7B%7D%5D&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1685549826179&to_ts=1685722626179&live=true)

1. The tx arrives to the sequencer at 16:38:26
2. At 16:38:32 an attempt is made to add this tx into the open batch (25479), but it cannot do because it overflows the remaining counters left in the batch. In this case, the counters for that tx are updated and it is put back in the list of pending txs (with its recalculated efficiency)
3. At 16:40:43 it is reprocessed again but in batch 25481 and it is processed correctly. It is reprocessed 2 batches later because its efficiency (when updating counters of the tx) was probably worse than other pending txs in the efficiency list. But finally it's processed correctly, it takes around 2 minutes, but due to that "update" of the counters
