### ISSUE TITLE
Question: Why isn't zkEVM directly built on top of zkWASM?

### ISSUE THREAD

**Issue by 0xZhiyuan** [0xPolygonHermez/zkevm-node#2268]
Hello,

I have a question regarding the design choice for zkEVM.

Why isn't zkEVM directly built on top of zkWASM? In theory, we can simply compile the Ethereum Virtual Machine (EVM) into WebAssembly (WASM) and then have it run on zkWASM. I'm curious about the specific reasons why this path was not chosen.

Would the potential conversion complexities and possible performance issues outweigh the benefits of a more general-purpose solution like WASM?

I appreciate your time and look forward to your response.

**Comment by jbaylina** [comment]
Mainly because efficiency. The arithmetization of the zkEVM has a lot of taylor made state machines specially designed for the EVM.  For example, the arithmetic and the binary state machins are 256 bits. Wr have a special keccak sm. The storage is a SMT adapted to goldilocks. And the memory are words of 256bits with a special sm that allows unaligned reads and writes.
Also the processor itself is designed with nonDeterminism in mind, and the zkAsm that we designed is prepared for some tricks in the wittness computation. 

But said that, it's possible that when zkTech evolves the approach that you proposed could make sense. There are other teams that are thinking in using riskV. 

I don't have a crystal ball here, but I don't see this approach practical in the upcoming years.
