### ISSUE TITLE
Add Upper Limit on `RPC` Batch Requests

### ISSUE THREAD

**Issue by Psykepro** [0xPolygonHermez/zkevm-node#2307]
# Overview:

There's a need to improve our system's handling of batched requests. Currently, the system does not enforce restrictions on the number of batched requests.

## Recommended Changes:

1. **Control Over Batch Requests:**
   - Introduce a new config parameter `RPC.BatchRequestsEnabled`, with a default value of `false`, which will allow enabling or disabling batch requests via HTTP.
   - Introduce a new config parameter `RPC.BatchRequestsLimit`, with a default value of `20`, which will limit the number of requests that can be incorporated into each batch request. If this parameter is set to zero, there will be no limit on the number of requests in a batch.

## Objective:

The recommended improvements aim to streamline the system's processing of batch requests. These changes will ensure the system's capability to efficiently manage a large number of requests within a single batch, thus enhancing overall operational efficiency. By limiting the number of requests in a batch and allowing batch requests to be enabled or disabled via configuration, we can help maintain system performance without unnecessary memory pressure.

**Comment by Psykepro** [comment]
.

**Comment by tclemos** [comment]
batch request is a feature provided by design when implementing a json-RPC 2.0 server, source: https://www.jsonrpc.org/specification#batch

I've tested some providers and was able to send many jRPC requests at once without any problem when querying data from L1.

The node already has configurations to set the `Read` and `Write` limits for the time it takes to handle the jRPC requests.

I agree that we could add configurable limitations for the number of requests in a single batch and also the size of the batch request, negative values should not be allowed and the value `0(zero)` should represent `no limit`, allowing the node owner to define its limits accordingly to its resources.
