### ISSUE TITLE
Failed to get balance from state error

### ISSUE THREAD

**Issue by jleeqn** [0xPolygonHermez/zkevm-node#2319]
#### System information
zkEVM Node version: `v0.1.2`
OS & Version: `Linux`
Network: `Mainnet`
#### Expected behavior 
No error
#### Actual behavior
Sometimes the method `eth_getBalance` still gets the error message `failed to get balance from state`.
#### Steps to reproduce the behavior
```
curl http://127.0.0.1:8545 \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_getBalance","params":["0xfc92bcb548e630f82cdce642334f6b39847c92cb","latest"],"id":5005,"jsonrpc":"2.0"}'
```
```
Jul 24 07:11:51 zkevm-node[27116]: 2023-07-24T07:11:51.283Z        INFO        jsonrpc/handler.go:144        failed call: [-32000]failed to get balance from state. Params: ["0x68af128c601ef3109ef7542cd4b15dfcf2766e4a","latest"]        {"pid": 27116, "version": "v0.1.2", "method": "eth_getBalance", "requestId": 645011}
Jul 24 07:11:51 zkevm-node[27116]: 2023-07-24T07:11:51.284Z        INFO        jsonrpc/handler.go:144        failed call: [-32000]failed to get balance from state. Params: ["0xedc7c0a67c150b31740d1eff1ed26fa7c66eecf3","latest"]        {"pid": 27116, "version": "v0.1.2", "method": "eth_getBalance", "requestId": 645012}
```
_Originally posted by @jleeqn in https://github.com/0xPolygonHermez/zkevm-node/issues/1823#issuecomment-1647633706_

**Comment by tclemos** [comment]
@jleeqn we made some improvements and fixes to the network since then, could you please double-check if you are still facing the issues?

Before testing it, please make sure to run the versions specified here: https://github.com/0xPolygonHermez
These are the instructions to guide you while updating the environment to the specified versions: https://polygontechnology.notion.site/Mainnet-Beta-UPDATE-zkEVM-Node-version-0-3-0-or-to-0-2-5-e150867951cd46c088f6d6c03b2cb5db
