### ISSUE TITLE
What is the -am flag in zkevm-approve and what does the approve step do?

### ISSUE THREAD

**Issue by Annihilatopia** [0xPolygonHermez/zkevm-node#2442]
Hi there, in your docker compose;

https://github.com/0xPolygonHermez/zkevm-node/blob/659b082546c00178e7dbebabf0e8b6f2d914b167/test/docker-compose.yml#L352-L364

what does the `-am` flag mean and how do I populate it on a custom deployment?

**Comment by tclemos** [comment]
It's the amount of MATIC you want to approve in order to allow the rollup SC to pay the Aggregator on behalf of the Sequencer when a sequence proof is generated.

here is the flag definition: https://github.com/0xPolygonHermez/zkevm-node/blob/659b082546c00178e7dbebabf0e8b6f2d914b167/cmd/main.go#L139-L144
