### ISSUE TITLE
Wrong transaction confirmation time

### ISSUE THREAD

**Issue by amitOodles** [0xPolygonHermez/zkevm-node#2512]
#### System information

zkEVM Node version: `v0.0.8`
OS & Version: `Linux`
Network: `Other`

I am running a ZkEVM L2 network using Sepolia as the L1 network, sometimes when i instantiate a transaction on the L2 network, metamask shows that the confirmation time is actually before the transaction instantiation time.

#### Expected behaviour
The transaction confirmation time should be after the transaction instantiation time. For example if a transaction is initiated at 11 AM the confirmation time should be after 11 AM.

#### Actual behaviour
But in my case, the confirmation time shown is earlier than the transaction instantiation time. For an example in one transaction - i submitted the transaction at 11:56 AM but the confirmation time is 10:48 AM.
 
#### Images
![image_2023_09_05T16_52_08_341Z](https://github.com/0xPolygonHermez/zkevm-node/assets/20085459/eca6437a-defa-493e-96d9-949b8c7c54cb)

**Comment by obynonwane** [comment]
You might need to update your node version and confirm if the behavior is still the same. There have been quite a number of important update since your current node version

The current test has the following version
Testnet updated:
zkevm-prover:v2.2.0
zkevm-node:v0.3.0

**Comment by amitOodles** [comment]
@obynonwane 

I have set up a local network using the zkevm-node release 0.3.0 and still facing issue in confirmation time. Attaching the image below

![Screenshot from 2023-09-07 12-42-07](https://github.com/0xPolygonHermez/zkevm-node/assets/20085459/8fd59d5b-4633-4dee-9a61-e5eaef195664)
![Screenshot from 2023-09-07 14-44-50](https://github.com/0xPolygonHermez/zkevm-node/assets/20085459/50718ffe-4632-4e4f-9742-e3e4b9de3288)

**Comment by amitOodles** [comment]
@agnusmor any update ?

**Comment by Psykepro** [comment]
@amitOodles 
Thank you for bringing this to our attention. We understand that the discrepancy in the timestamp might be confusing, especially when you observe that the confirmation time is earlier than the transaction instantiation time. Let me clarify the behavior you're seeing.

In the current implementation of the `zkEVM-node`, when transactions are added to a batch, the timestamp used for confirmation is based on the `batch.timestamp`. This is essentially when the batch was opened. The rationale behind this approach is to ensure that all nodes have a consistent timestamp, which is essential for the consistent calculation of the hash for the state root. Given the current system's architecture, if we used different timestamps for each node, it would impact the calculated hash, leading to discrepancies. Moreover, since we don't send L2 block information with the rollup info to the L1, synchronizing based on individual transaction timestamps is challenging.

As a result, in some cases, the batch's opening timestamp (used as the confirmation time) might be earlier than the exact time a transaction is instantiated. This is because the batch is always created before the transaction is received by the node.

However, you can adjust this behavior to some extent. By modifying the `Sequencer.Finalizer.TimestampResolution` parameter in the toml config to a lower value, you can make the node close batches more frequently. This would reduce the time difference between the batch's timestamp and the transaction's instantiation time. But please note, while this may minimize the time window of discrepancy, it might lead to increased costs due to more frequent batch closures.

We genuinely appreciate your feedback and patience regarding this matter. We're continuously working to improve the zkEVM-node, and I'm pleased to inform you that we're addressing this timestamp concern in the upcoming `Fork Id 6`. This will provide a more intuitive and accurate timestamp experience.

Thank you for your understanding and support as we work to enhance the system.
