### ISSUE TITLE
add tests to check Executor response for reverted txs

### ISSUE THREAD

**Issue by tclemos** [0xPolygonHermez/zkevm-node#3288]
check if reverted TXs have their logs discarded.

scenarios to test:
- batch with single block:
  - single reverted tx
  - multiple txs, but first tx reverts
  - multiple txs, but last tx reverts
  - multiple txs, but first and last tx reverts
  - multiple txs, but first and last tx succeed while some tx in the middle reverts
  - multiple txs, but all txs reverts

- batch with multiple blocks:
  - mix 2 blocks generated above
  - mix 3 blocks generated above
  - mix all blocks generated above

**Comment by Antiquedavidsauce27** [comment]
Hello users, do you have any issue with your wallet and Have you Rectificate your wallet due to the KYC verification process in accordance with the new KYC Registration agreement. As a result,we regret to inform you that all unverified accounts with their associated assets will be frozen effective immediately
