### ISSUE TITLE
Possible wrong data on block 0 and  batch 0

### ISSUE THREAD

**Issue by xavier-romero** [0xPolygonHermez/zkevm-node#3330]
#### System information

zkEVM Node version: `0.5.12`
Network: `Mainnet`

#### Expected behaviour
Right answer

#### Actual behaviour

- Block 0 reports null miner, while it should be 0x0000000000000000000000000000000000000000000000000000000000000000 though.
- Also, batch 0 reports a wrong timestamp (looks like an overflow).

#### Steps to reproduce the behaviour
Block 0:
`curl -s -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","id":1,"method":"eth_getBlockByNumber","params":["0x0",true]}' https://zkevm-rpc.com | jq .result.miner -r`
--> null
Batch 0:
`curl -s -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","id":1,"method":"zkevm_getBatchByNumber","params":["0x0",true]}' https://zkevm-rpc.com | jq -r .result.timestamp`
--> 0xfffffff1886e0900

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by tclemos** [comment]
The miner as null was fixed by [this PR](https://github.com/0xPolygonHermez/zkevm-node/pull/3274) and will be available in the node `v0.5.13` version

I've found the problem with the Timestamp, it's a read-only issue, so we can fix it without affecting the network.

Basically what's happening is that before Etrog the batch timestamp was generated by the `Sequencer` when the batch was created in the trusted state, but on Etrog, the batch timestamp is defined only when the batch is virtualized.

There is a logic in the node to identify if the batch was generated before or after Etrog, and for that we use the forkID data, as you can see in the image.

![image](https://github.com/0xPolygonHermez/zkevm-node/assets/1298871/e89a10ad-24aa-4097-8989-371cccffeb1f)


The problem in this case is happening because the batch/forkID table doesn't take into account the batch 0, because it starts on batch 1.

When a forkID is not found in the data, the node considers the current forkID as default. In this case the node is assuming the batch 0 was generated using Etrog rules, and since batch 0 is the genesis batch and there is no virtualization data to it, the timestamp is null when it's considered as Etrog.

here is what's happening:

- gets the batch timestamps from the batch and virtual batch data
- get forkID for batch 0, but since batch 0 is not in the forkID table, no row is returned
- since no forkID is not found, fallback to the default forkID, which is 7 because it's the current one
- since forkID is 7(Etrog), we must return the virtualized batch timestamp
- since the batch 0 is not virtualized, the timestamp is loaded as null, then a default value is set 0001-01-01T00:00:00Z
- the batch timestamp needs to be returned in a hex decimal that represents the unix epoch of the timestamp
- the unix epoch for 0001-01-01T00:00:00Z is -62135596800
- since batch timestamp is a uint64 it cannot have negative values 
- the result of a uint64(-62135596800) is 18446744011573954816
- 18446744011573954816 in hex is 0xfffffff1886e0900
